title: Web dev and more
description: Blog where I share my programming and web development experiences 

url: http://kabaehr.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

future: false

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: kabaehr
   twitter: kabaehr
   email: katharina.baehr@zuehlke.com

google_analytics: "UA-78631003-2"
